# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

spatial_zones <- function(locs, k) {
    .Call(`_multinomss_spatial_zones`, locs, k)
}

temporal_zones <- function(centroid_zones, dates, time_prop, max_time) {
    .Call(`_multinomss_temporal_zones`, centroid_zones, dates, time_prop, max_time)
}

zones <- function(locs, k, dates, time_prop, max_time) {
    .Call(`_multinomss_zones`, locs, k, dates, time_prop, max_time)
}

multinom_scan <- function(zones, group, levels) {
    .Call(`_multinomss_multinom_scan`, zones, group, levels)
}

multinom_mlc <- function(zones, group, id, levels) {
    .Call(`_multinomss_multinom_mlc`, zones, group, id, levels)
}

multinom_permutation <- function(zones, group, levels, n_perm) {
    .Call(`_multinomss_multinom_permutation`, zones, group, levels, n_perm)
}

p_val <- function(stats, perm) {
    .Call(`_multinomss_p_val`, stats, perm)
}

