# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculates the spatial zones, starting with each centroid and increasing size
#' from 1 to pre-specified k points. These represent circular zones in space.
#' 
#' @param locs An n x 2 matrix of centroid point coordinates in latitude/longitude
#' @param spatial_prop A float/decimal specifying the maximum proportion of the total population to be included in the scanning windows
#' @export
spatial_zones <- function(locs, spatial_prop) {
    .Call(`_multinomss_spatial_zones`, locs, spatial_prop)
}

#' Takes spatial zone input and calculates the temporal zones. For each circular
#' zone in space, it effectively varies the height to create cylindrical zones.
#'
#' @param zones A list of spatial zones produced by \code{spatial_zones()} function
#' @param dates A vector containing the dates associated with each observation. If time aggregation is used, this will correspond to time interval that each observation falls into
#' @param time_prop A float/decimal specifying the maximum proportion of the study length to consider as a cluster
#' @param study_length An integer specifying the length of the study in days
#' @param retrospective A logical T/F that specifies whether a retrospective analysis is desired. If \code{retrospective = F} the prospective zones will be calculated
temporal_zones <- function(zones, dates, time_prop, study_length, retrospective) {
    .Call(`_multinomss_temporal_zones`, zones, dates, time_prop, study_length, retrospective)
}

#' Performs calculation of both spatial and temporal zones in one step. The arguments are the same as specified in \code{spatial_zones()} and \code{temporal_zones()}
#' @export
zones <- function(locs, spatial_prop, dates, time_prop, study_length, retrospective) {
    .Call(`_multinomss_zones`, locs, spatial_prop, dates, time_prop, study_length, retrospective)
}

multinom_scan <- function(zones, group, levels) {
    .Call(`_multinomss_multinom_scan`, zones, group, levels)
}

#' Calculates the max distance between points within a cluster. This corresponds to the radius of the cluster
#' 
#' @param idlist A list of vectors containing the ID's in each cluster
#' @param idvec A vector of ids that are associated with each observation
#' @param locs A matrix of coordinates for each observation/centroid
max_dist <- function(idlist, idvec, locs) {
    .Call(`_multinomss_max_dist`, idlist, idvec, locs)
}

#' Calculates the most likely cluster for each centroid point by calculating the test statistic for all scanning windows
#' 
#' @param zones list of space-time scanning windows
#' @param group vector corresponding to group membership of each observation
#' @param id vector corresponding to the ID number of the observation
#' @param levels vector denoting the unique levels of the group variable to which an observation can belong
#' @export
multinom_mlc <- function(zones, group, id, levels) {
    .Call(`_multinomss_multinom_mlc`, zones, group, id, levels)
}

#' Conducts the permutations needed for Monte Carlo hypothesis testing
#' 
#' @param zones list of space-time scanning windows
#' @param group vector corresponding to group membership of each observation
#' @param n_perm number of Monte Carlo permutations to perform
#' @export
multinom_permutation <- function(zones, group, levels, n_perm) {
    .Call(`_multinomss_multinom_permutation`, zones, group, levels, n_perm)
}

#' Calculates the p-values from the Monte Carlo permutation-generated test statistics
#' 
#' @param stats vector of test statistics from the data for which p-values are desired
#' @param perm vector of permutation test statistics used to compute p-values
#' @export
p_val <- function(stats, perm) {
    .Call(`_multinomss_p_val`, stats, perm)
}

non_overlap <- function(ids) {
    .Call(`_multinomss_non_overlap`, ids)
}

